package com.ipcam.internalevent;

public enum InternalEvent
{
	NEED_TO_COLLECT_DATA,
	NEED_TO_RECORD_AMBIENT_SOUND,
	RENEW_BATTERY_LEVEL,
	NO_BROADCAST_FROM_PHOTO_ACTIVITY,
	NETWORK_CONNECTED,
	NETWORK_DISCONNECTED,
	ADMIN_CONNECTED,
	NOTIFY_USER_URGENTLY,
	NOTIFY_USER,
	TASK_COMPLETE
}